version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment: -NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - nextjs
    ports: -"80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
